# python and jupyter basics

In [21]:
# vars
x = 5
print(x*5 + 2)

27


In [22]:
# lists and tuples
y = [5, 4, 3]
print("y[0] =", y[0])
y.append(("asdf", "ghjk"))
print("y[1:3] =", y[1:3])
y.append(2)
print("y[3:] =", y[3:])
print("y[-1] =", y[-1])
y.pop()
x, a = y[-1]
print("x =", x, " a =", a)
y

y[0] = 5
y[1:3] = [4, 3]
y[3:] = [('asdf', 'ghjk'), 2]
y[-1] = 2
x = asdf  a = ghjk


[5, 4, 3, ('asdf', 'ghjk')]

In [23]:
# dictionary
d = {5: "asdf", "a": 3}
str(d["a"]) + d[5]

'3asdf'

In [25]:
if (y[0]==5 and (y[1]==2 or y[-1][0] < "az")):
    print("true")
else:
    print("false")

true


In [5]:
for x in y:
    print(x)

for i in range(5):
    print(i)

for i in range(0, 100, 30):
    print(i)
    
for i, x in enumerate(y):
    print("x[", i, "] = ", x, sep='')
    
[x**3 for x in range(6)]

5
4
3
('asdf', 'ghjk')
0
1
2
3
4
0
30
60
90
x[0] = 5
x[1] = 4
x[2] = 3
x[3] = ('asdf', 'ghjk')


[0, 1, 8, 27, 64, 125]

In [6]:
# functions

def f(x, y):
    return x+2*y

y = 0
def addy(x):
    global y
    y+=x
    return y

print(addy(f(y=2, x=3)), addy(6))

def sq():
    for i in range(100):
        yield i*i

for x in sq():
    if x > 20:
        break
    print(x)

7 13
0
1
4
9
16


In [7]:
# classes

class A:
    def __init__(self, a, b):
        self.a, self.b = a, b
    def s(self):
        return self.a + self.b
    def add(self, a):
        self.a += a
        
a = A(4, 5)
print(a.a, a.b)
a.add(4)
print("a.s() =", a.s())

class B(A):
    def add(self, a):
        super().add(a)
        self.b += a
        
b = B(4, 5)
b.add(4)
print("b.s() =", b.s())

4 5
a.s() = 13
b.s() = 17


# numpy

In [8]:
import numpy as np


a = np.array([x for x in range(20)])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
a[2:5]

array([2, 3, 4])

In [10]:
b = np.zeros((2, 4, 5))
b

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
b[:, 2:, :3]

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
a = a.reshape((4, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
b[0] = b[0]+a
b[1] = a*a
b

array([[[  0.,   1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.],
        [ 15.,  16.,  17.,  18.,  19.]],

       [[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]]])

In [14]:
b += 2
b

array([[[  2.,   3.,   4.,   5.,   6.],
        [  7.,   8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.,  16.],
        [ 17.,  18.,  19.,  20.,  21.]],

       [[  2.,   3.,   6.,  11.,  18.],
        [ 27.,  38.,  51.,  66.,  83.],
        [102., 123., 146., 171., 198.],
        [227., 258., 291., 326., 363.]]])

In [15]:
b > 100

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [16]:
b += np.array([1, 2, 3, 4, 5])
b

array([[[  3.,   5.,   7.,   9.,  11.],
        [  8.,  10.,  12.,  14.,  16.],
        [ 13.,  15.,  17.,  19.,  21.],
        [ 18.,  20.,  22.,  24.,  26.]],

       [[  3.,   5.,   9.,  15.,  23.],
        [ 28.,  40.,  54.,  70.,  88.],
        [103., 125., 149., 175., 203.],
        [228., 260., 294., 330., 368.]]])

In [17]:
b += np.array([4, 3, 2, 1])

ValueError: operands could not be broadcast together with shapes (2,4,5) (4,) (2,4,5) 

In [ ]:
b += np.array([4, 3, 2, 1]).reshape(1, 4, 1)
b

In [ ]:
b[b>50] = b[b>50]%50
b

In [ ]:
b[[0, 0, 1], :2, 3:]

In [ ]:
b = b[:, [3, 2, 1, 0]]
b

In [ ]:
np.mean(b)

In [ ]:
np.mean(b, axis=0)

In [ ]:
np.mean(b, axis=1)

In [ ]:
np.max(b, axis=2)

In [ ]:
np.argmax(b, axis=2)

In [ ]:
c = np.round(np.random.normal(size=(2, 3))*3)
c

In [ ]:
d = np.round(np.random.normal(10, 4, size=(3, 5)))
d

In [ ]:
np.matmul(c, d)

# pandas

In [ ]:
import pandas as pd

In [ ]:
x = pd.Series([x**2 for x in range(10)])
x

In [ ]:
df = pd.DataFrame({
                    'A': x, 
                    'B': [1, 2]*5,
                    'C': [True, False, True, True, False]*2, 
                    'D': np.random.normal(size=10), 
                    'E': list(map(lambda x: "Male" if x>0 else "Female", np.random.normal(size=10)))
                  })
df

In [ ]:
df[['A', 'C']].head(5)

In [ ]:
df[5:8]

In [ ]:
df.describe()

In [ ]:
df.loc[5:8, ['A', 'D', 'E']]

In [ ]:
df.E

In [ ]:
df[df.A > 50]

In [ ]:
df['isMale'] = df.E == 'Male'
df

In [ ]:
df = df.drop(columns = 'E')
df

In [ ]:
df.C = df.C*1
df.isMale = df.isMale*1
df

In [ ]:
df.describe()

In [ ]:
data = pd.read_csv("digidb/DigiDB_digimonlist.csv")
data.head(10)

In [ ]:
data.describe()

In [ ]:
data.loc[data.Number%2==0, 'Number'] = float('nan')
data.head(10)

In [ ]:
data.describe()

In [ ]:
data.isna().head(10)

In [ ]:
data.isna().sum()

In [ ]:
data['Number'] = data['Number'].fillna(data['Number'].mean())
data.head(10)

# pyplot

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot([x**2 for x in range(10)])
plt.show()

In [ ]:
a = list(range(7))
b = a
c = [x**2 for x in a]
d = [2**x for x in a]
plt.plot(a, b, 'bo')
plt.plot(a, c, 'rs')
plt.plot(a, d, 'g-')
plt.axis([-1, 7, -1, None])
plt.show()

In [ ]:
xd = {
    'x': np.random.rand(100)*100,
    'color': np.random.randint(0, 100, size=100),
    'size': np.random.rand(100)*100
}
xd['y'] = xd['x']/2 + np.random.normal(0, 10, size=100)
plt.figure(figsize=(10, 10))
plt.scatter('x', 'y', c='color', s='size', data=xd)
plt.show()

In [ ]:
plt.scatter('Lv 50 HP', 'Lv50 Def', data=data)
plt.xlabel("HP")
plt.ylabel("Defense")
plt.show()

In [ ]:
names = ["pesho", "gosho", "tosho"]
values = [10, 50, 100]
plt.bar(names, values)
plt.show()

In [ ]:
names = data['Attribute'].unique()
values = [data.loc[data['Attribute'] == x, "Lv50 Atk"].mean() for x in names]
plt.bar(names, values)

In [ ]:
names = data['Attribute'].unique()
values1 = [data.loc[data['Attribute'] == x, "Lv50 Atk"].mean() for x in names]
values2 = [data.loc[data['Attribute'] == x, "Lv50 Atk"].max() for x in names]
values3 = [data.loc[data['Attribute'] == x, "Lv50 Atk"].min() for x in names]
plt.figure(figsize=(30, 10))
plt.subplot(1, 3, 1)
plt.bar(names, values1)
plt.ylabel("mean")
plt.subplot(1, 3, 2)
plt.bar(names, values2)
plt.ylabel("max")
plt.subplot(1, 3, 3)
plt.bar(names, values3)
plt.ylabel("min")